# Generated by Django 4.1.2 on 2022-12-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkec',
            options={'verbose_name': 'Ход ЭК', 'verbose_name_plural': 'Ход ЭК'},
        ),
        migrations.AlterModelOptions(
            name='contractnames',
            options={'verbose_name': 'Разделы ЭК', 'verbose_name_plural': 'Разделы ЭК'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отдел'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперт'},
        ),
        migrations.AddField(
            model_name='checkec',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkec',
            name='contractName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pao.contractnames', verbose_name='Номер пункта'),
        ),
        migrations.AlterField(
            model_name='checkec',
            name='onReview',
            field=models.IntegerField(verbose_name='На проверке'),
        ),
        migrations.AlterField(
            model_name='checkec',
            name='verified',
            field=models.IntegerField(verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='contractnames',
            name='descriptionEC',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contractnames',
            name='expertEC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pao.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='contractnames',
            name='sectionEC',
            field=models.CharField(max_length=5, verbose_name='Номер пункта'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pao.department', verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='fioExpert',
            field=models.CharField(max_length=50, verbose_name='ФИО эксперта'),
        ),
    ]
