# Generated by Django 4.1.2 on 2022-12-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0003_department_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='shortName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сокращенное название'),
        ),
    ]
