# Generated by Django 4.1.2 on 2022-12-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0005_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkec',
            name='onReview',
        ),
        migrations.AddField(
            model_name='checkec',
            name='declared',
            field=models.IntegerField(default=0, verbose_name='Заявлено'),
            preserve_default=False,
        ),
    ]
