# Generated by Django 4.1.4 on 2022-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0006_remove_checkec_onreview_checkec_declared'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnames',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
