# Generated by Django 4.1.4 on 2023-01-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0007_contractnames_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
                'ordering': ('name',),
            },
        ),
    ]
