# Generated by Django 4.1.4 on 2023-07-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableBases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('base_id', models.CharField(max_length=150, verbose_name='ID базы')),
            ],
            options={
                'verbose_name': 'Базы Airtable',
                'verbose_name_plural': 'Базы Airtable',
            },
        ),
        migrations.CreateModel(
            name='GoogleMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование листа')),
                ('id_sheet', models.CharField(max_length=150, verbose_name='ID листа')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к отчету')),
                ('status', models.BooleanField(default=True, verbose_name='Запущено?')),
            ],
            options={
                'verbose_name': 'Мониторинг',
                'verbose_name_plural': 'Мониторинг',
            },
        ),
        migrations.CreateModel(
            name='LogsCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения выполнения')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование задачи')),
                ('status', models.CharField(max_length=155, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Логирование CRON',
                'verbose_name_plural': 'Логирование CRON',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование запроса')),
                ('body', models.TextField(verbose_name='Запрос')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к запросу')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='GoogleMonitoringFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('spreadsheet_id', models.CharField(max_length=255, verbose_name='ID документа')),
                ('monitoring', models.ManyToManyField(related_name='monitoring_files', to='system.googlemonitoring', verbose_name='Мониторинг')),
            ],
            options={
                'verbose_name': 'Мониторинг файл',
                'verbose_name_plural': 'Мониторинг файл',
            },
        ),
        migrations.AddField(
            model_name='googlemonitoring',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.query', verbose_name='Запрос на формирование'),
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='Ключ')),
                ('user', models.ManyToManyField(related_name='key_users_google', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Ключи Google',
                'verbose_name_plural': 'Ключи Google',
            },
        ),
        migrations.CreateModel(
            name='AirtableTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('table_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID таблицы')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к таблице')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.airtablebases', verbose_name='База Airtable')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.query', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Таблицы Airtable',
                'verbose_name_plural': 'Таблицы Airtable',
            },
        ),
        migrations.CreateModel(
            name='AirtablePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=155, null=True, verbose_name='API ключ')),
                ('user', models.ManyToManyField(related_name='key_user_air', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Ключи Air',
                'verbose_name_plural': 'Ключи Air',
            },
        ),
    ]
