# Generated by Django 4.1.4 on 2023-01-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pao', '0008_post'),
        ('main', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pao.post', verbose_name='Должность'),
        ),
    ]
