# Generated by Django 4.1.4 on 2023-04-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EduLevel',
            new_name='EduLevelProgram',
        ),
        migrations.AlterModelOptions(
            name='edulevelprogram',
            options={'verbose_name': 'Уровень подготовки направления', 'verbose_name_plural': 'Уровень подготовки направления'},
        ),
    ]
