# Generated by Django 4.1.4 on 2023-04-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0002_rename_edulevel_edulevelprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edulevelprogram',
            name='tandem_name',
            field=models.CharField(default='', max_length=50, verbose_name='Наименование в Tandem'),
            preserve_default=False,
        ),
    ]
