# Generated by Django 4.1.4 on 2023-04-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0003_edulevelprogram_tandem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='developeform',
            name='sort',
            field=models.SmallIntegerField(default=1, verbose_name='Индекс для сортировки'),
            preserve_default=False,
        ),
    ]
