# Generated by Django 4.1.4 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0005_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='Ключ'),
        ),
    ]
