# Generated by Django 4.1.4 on 2023-04-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0006_alter_google_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='file',
        ),
        migrations.AddField(
            model_name='google',
            name='creds',
            field=models.JSONField(default={'123': 123}, verbose_name='Creds'),
            preserve_default=False,
        ),
    ]
