# Generated by Django 4.1.4 on 2023-05-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0007_remove_google_file_google_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='creds',
        ),
    ]
