# Generated by Django 4.1.4 on 2023-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0010_alter_googlereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereport',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к отчету'),
        ),
    ]
