# Generated by Django 4.1.4 on 2023-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0011_googlereport_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlereport',
            options={'verbose_name': 'Отчеты в Google', 'verbose_name_plural': 'Отчеты в Google'},
        ),
        migrations.AddField(
            model_name='googlereport',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на отчет'),
        ),
    ]
