# Generated by Django 4.1.4 on 2023-05-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0012_alter_googlereport_options_googlereport_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereport',
            name='spreadsheet_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID документа'),
        ),
    ]
