# Generated by Django 4.1.4 on 2023-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0013_googlereport_spreadsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereport',
            name='spreadsheet_id',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='ID документа'),
        ),
    ]
