# Generated by Django 4.1.4 on 2023-06-27 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oopk', '0015_googlereport_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='user',
        ),
        migrations.AddField(
            model_name='google',
            name='user',
            field=models.ManyToManyField(related_name='key_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
