# Generated by Django 4.1.4 on 2023-06-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0016_remove_google_user_google_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование запроса')),
                ('query', models.TextField(verbose_name='Запрос')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к запросу')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование листа')),
                ('id_sheet', models.CharField(max_length=150, verbose_name='ID листа')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к отчету')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopk.query', verbose_name='Запрос на формирование')),
            ],
        ),
    ]
