# Generated by Django 4.1.4 on 2023-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0018_alter_googlemonitoring_options_alter_query_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemonitoring',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Запущено?'),
        ),
    ]
