# Generated by Django 4.1.4 on 2023-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0019_googlemonitoring_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemonitoring',
            name='name_file',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Наименование документа'),
        ),
    ]
