# Generated by Django 4.1.4 on 2023-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0020_googlemonitoring_name_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemonitoring',
            name='name_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование документа'),
        ),
    ]
