# Generated by Django 4.1.4 on 2023-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0021_alter_googlemonitoring_name_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlemonitoring',
            name='name_file',
        ),
        migrations.CreateModel(
            name='GoogleMonitoringFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('monitoring', models.ManyToManyField(related_name='monitoring_files', to='oopk.googlemonitoring', verbose_name='Мониторинг')),
            ],
        ),
    ]
