# Generated by Django 4.1.4 on 2023-06-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0022_remove_googlemonitoring_name_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlemonitoringfiles',
            options={'verbose_name': 'Мониторинг файл', 'verbose_name_plural': 'Мониторинг файл'},
        ),
    ]
