# Generated by Django 4.1.4 on 2023-06-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0023_alter_googlemonitoringfiles_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleMonitoringFiles',
        ),
    ]
