# Generated by Django 4.1.4 on 2023-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0024_delete_googlemonitoringfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMonitoringFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('spreadsheet_id', models.CharField(max_length=255, verbose_name='ID документа')),
                ('monitoring', models.ManyToManyField(related_name='monitoring_files', to='oopk.googlemonitoring', verbose_name='Мониторинг')),
            ],
            options={
                'verbose_name': 'Мониторинг файл',
                'verbose_name_plural': 'Мониторинг файл',
            },
        ),
    ]
