# Generated by Django 4.1.4 on 2023-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0025_googlemonitoringfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения выполнения')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование задачи')),
                ('status', models.CharField(max_length=155, verbose_name='Статус')),
            ],
        ),
    ]
