# Generated by Django 4.1.4 on 2023-06-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0026_logscron'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logscron',
            options={'verbose_name': 'Логирование CRON', 'verbose_name_plural': 'Логирование CRON'},
        ),
    ]
