# Generated by Django 4.1.4 on 2023-07-02 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oopk', '0027_alter_logscron_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableBases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('base_id', models.CharField(max_length=150, verbose_name='ID базы')),
            ],
            options={
                'verbose_name': 'Базы Airtable',
                'verbose_name_plural': 'Базы Airtable',
            },
        ),
        migrations.AlterModelOptions(
            name='google',
            options={'verbose_name': 'Ключи Google', 'verbose_name_plural': 'Ключи Google'},
        ),
        migrations.AlterModelOptions(
            name='googlereport',
            options={'verbose_name': 'Отчеты Google', 'verbose_name_plural': 'Отчеты Google'},
        ),
        migrations.AlterField(
            model_name='google',
            name='user',
            field=models.ManyToManyField(related_name='key_users_google', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.CreateModel(
            name='AirtableTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('table_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID таблицы')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к таблице')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopk.airtablebases', verbose_name='База Airtable')),
            ],
            options={
                'verbose_name': 'Таблицы Airtable',
                'verbose_name_plural': 'Таблицы Airtable',
            },
        ),
        migrations.CreateModel(
            name='Airtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=155, null=True, verbose_name='API ключ')),
                ('user', models.ManyToManyField(related_name='key_users_air', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Ключи Air',
                'verbose_name_plural': 'Ключи Air',
            },
        ),
    ]
