# Generated by Django 4.1.4 on 2023-07-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0028_airtablebases_alter_google_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtabletables',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oopk.query', verbose_name='Запрос'),
        ),
    ]
