# Generated by Django 4.1.4 on 2023-07-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0029_airtabletables_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtabletables',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopk.query', verbose_name='Запрос'),
        ),
    ]
