# Generated by Django 4.1.4 on 2023-07-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0030_alter_airtabletables_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='query_body',
        ),
    ]
