# Generated by Django 4.1.4 on 2023-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopk', '0033_rename_airtable_airtablepersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtablepersonal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='airtabletables',
            name='base',
        ),
        migrations.RemoveField(
            model_name='airtabletables',
            name='query',
        ),
        migrations.RemoveField(
            model_name='google',
            name='user',
        ),
        migrations.RemoveField(
            model_name='googlemonitoring',
            name='query',
        ),
        migrations.RemoveField(
            model_name='googlemonitoringfiles',
            name='monitoring',
        ),
        migrations.DeleteModel(
            name='LogsCron',
        ),
        migrations.DeleteModel(
            name='AirtableBases',
        ),
        migrations.DeleteModel(
            name='AirtablePersonal',
        ),
        migrations.DeleteModel(
            name='AirtableTables',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='GoogleMonitoring',
        ),
        migrations.DeleteModel(
            name='GoogleMonitoringFiles',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
